# stages:
#   - build
#   - test

# create_file:
#   image: alpine
#   stage: build
#   script:
#     - echo "Creating a file ..."
#     - mkdir build
#     - touch build/test.txt
#   artifacts:
#     paths:
#       - build/

# test_file:
#   image: alpine
#   stage: test
#   script:
#     - test -f build/test.txt

stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client git
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" > id_rsa
    - chmod 600 id_rsa
    - ssh-add id_rsa
  script:
    - |
      ssh -o StrictHostKeyChecking=no ubuntu@13.60.255.157 << 'EOF'
        echo 'Connected, Success!'
        cd /var/www/flask-apache-ubuntu-host
        git pull origin main && echo 'Pulled latest changes!'
      EOF



