# stages:
#   - build
#   - test

# create_file:
#   image: alpine
#   stage: build
#   script:
#     - echo "Creating a file ..."
#     - mkdir build
#     - touch build/test.txt
#   artifacts:
#     paths:
#       - build/

# test_file:
#   image: alpine
#   stage: test
#   script:
#     - test -f build/test.txt
stages:
  - deploy

deploy_to_vm:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - echo "$SSH_PRIVATE_KEY"
    - echo "$SSH_PRIVATE_KEY" > private_key
    - chmod 600 private_key
  script:
    - echo "Testing SSH connection..."
    - ssh -o StrictHostKeyChecking=no -i private_key ubuntu@13.60.255.157 'echo "✅ Connected to server!"'
  when: manual


