# stages:
#   - build
#   - test

# create_file:
#   image: alpine
#   stage: build
#   script:
#     - echo "Creating a file ..."
#     - mkdir build
#     - touch build/test.txt
#   artifacts:
#     paths:
#       - build/

# test_file:
#   image: alpine
#   stage: test
#   script:
#     - test -f build/test.txt
stages:
  - deploy

deploy_to_vm:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - printf '%s\n' "$SSH_PRIVATE_KEY" | ssh-add -
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@13.60.255.157 'cd /var/www/flask-apache-ubuntu-host && git pull && source venv/bin/activate && sudo systemctl restart apache2'
  when: manual

