# stages:
#   - build
#   - test

# create_file:
#   image: alpine
#   stage: build
#   script:
#     - echo "Creating a file ..."
#     - mkdir build
#     - touch build/test.txt
#   artifacts:
#     paths:
#       - build/

# test_file:
#   image: alpine
#   stage: test
#   script:
#     - test -f build/test.txt

stages:
  - push

push_to_vm:
  stage: push
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client git
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" > id_rsa
    - chmod 600 id_rsa
    - ssh-add id_rsa
  script:
    - |
      ssh -o StrictHostKeyChecking=no ubuntu@13.60.255.157 << 'EOF'
        echo 'Connected, Success!'
        if [ -d /var/www/flask-apache-ubuntu-host ]; then
          cd /var/www/flask-apache-ubuntu-host || exit 1
          if [ -d .git ]; then
            echo "Git repo found, pulling latest changes..."
            git pull origin main && echo 'Pulled latest changes!'
          else
            echo "Directory exists but is not a git repo, cloning fresh..."
            sudo rm -rf /var/www/flask-apache-ubuntu-host/*
            git clone git@gitlab.com:manojtharindu11/flask-apache-ubuntu-host.git /var/www/flask-apache-ubuntu-host
          fi
        else
          echo "Directory does not exist, cloning repo..."
          git clone git@gitlab.com:manojtharindu11/flask-apache-ubuntu-host.git /var/www/flask-apache-ubuntu-host
        fi
        if [ -d .venv]; then
          echo "Virtual environment exists, activating..."
          source .venv/bin/activate
        else
          echo "Virtual environment does not exist, creating..."
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        fi
        if [ -f /etc/apache2/sites-available/flask-apache-ubuntu-host.conf ]; then
          echo "Apache config exists, reloading..."
          sudo cp flask-apache-ubuntu-host.conf /etc/apache2/sites-available/
          sudo a2enmod proxy
          sudo a2enmod proxy_http
          sudo a2ensite flask-apache-ubuntu-host.conf
          sudo systemctl reload apache2
        else
          echo "Apache config does not exist, setting up..."
          sudo cp flask-apache-ubuntu-host.conf /etc/apache2/sites-available/
          sudo a2enmod proxy
          sudo a2enmod proxy_http
          sudo a2ensite flask-apache-ubuntu-host.conf
          sudo systemctl reload apache2
        fi
        cd /var/www/flask-apache-ubuntu-host
        gunicorn --bind 127.0.0.1:8000 wsgi:app
      EOF
  only:
    - main